name: Build and Deploy to itch.io

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0 

      - name: Install dependencies
        run: dotnet restore

      - name: Build Blazor WebAssembly
        run: dotnet publish -c Release -o build_output

      - name: Zip the build output
        run: zip -r build.zip build_output

      - name: Deploy to itch.io from documentation
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: iheartfunnyreindeer
          ITCH_USER: totalg
          PACKAGE: build/windows
